Added fix for error:
RuntimeError: Error(s) in loading state_dict for EncoderDecoderModel:
	Missing key(s) in state_dict: "discriminator.lstm.weight_ih_l0", "discriminator.lstm.weight_hh_l0", "discriminator.lstm.bias_ih_l0", "discriminator.lstm.bias_hh_l0", "discriminator.fc.weight", "discriminator.fc.bias".